version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adminfiles-backend
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/admin_files.db:/app/admin_files.db
    environment:
      - DATABASE_URL=sqlite:admin_files.db
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_key_for_jwt_tokens_change_in_production}
      - JWT_EXPIRED_IN=60m
      - JWT_MAX_AGE=60
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminfiles-backend.rule=Host(`adminfiles.admingod.ch`) && PathPrefix(`/api`)"
      - "traefik.http.routers.adminfiles-backend.entrypoints=websecure"
      - "traefik.http.routers.adminfiles-backend.tls=true"
      - "traefik.http.services.adminfiles-backend.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adminfiles-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminfiles-frontend.rule=Host(`adminfiles.admingod.ch`)"
      - "traefik.http.routers.adminfiles-frontend.entrypoints=websecure"
      - "traefik.http.routers.adminfiles-frontend.tls=true"
      - "traefik.http.services.adminfiles-frontend.loadbalancer.server.port=80"
      - "traefik.http.middlewares.adminfiles-frontend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.adminfiles-frontend.middlewares=adminfiles-frontend-stripprefix"

networks:
  internal:
    driver: bridge
  proxy:
    external: true
